[tool.poetry]
name = "pic_organize"
version = "0.1.0"
description = "A basic Python project structure."
authors = []

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88

[tool.flake8]
max-line-length = 88
exclude = [".venv", "venv", "build", "dist", ".git", "__pycache__"]
